In [2]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [40]:
x = tf.Variable(3.0)

In [41]:
with tf.GradientTape() as tape:
    y=x**2

In [42]:
dy_dx = tape.gradient(y,x)

In [18]:
x=tf.random.uniform(shape=[2,3])*0.01
w=tf.random.uniform(shape=[2,1])
b=tf.random.uniform(shape=[2,1])

In [60]:
with tf.GradientTape() as tape:
    y= tf.add(tf.multiply(x, tf.transpose(w)), b)
    tf.print(y)

[[2.33529 3.53326821]
 [1.94069493 3.13867331]]


In [61]:
y_hat = tf.random.uniform(shape=[2, 3])
tf.print(y_hat)

[[0.932971716 0.449030876 0.410639167]
 [0.20943439 0.924947739 0.284496427]]


In [62]:
dy_dx =tape.gradient(y_hat,x)

In [63]:
print(dy_dx)

None


In [67]:
x = tf.ones((2, 2))
print("x", x)
with tf.GradientTape() as t:
    t.watch(x)
    y=tf.reduce_sum(x)
    print("\ny:",y)
    z= tf.multiply(y, y)
    print("\nz:", z)

dz_dx = t.gradient(z, x)
print("\ndz_dx", dz_dx)

x tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)

y: tf.Tensor(4.0, shape=(), dtype=float32)

z: tf.Tensor(16.0, shape=(), dtype=float32)

dz_dx tf.Tensor(
[[8. 8.]
 [8. 8.]], shape=(2, 2), dtype=float32)


In [75]:
dzx = dz_dx.numpy()

In [76]:
x=tf.Variable(1.0)
with tf.GradientTape() as t1:
    with tf.GradientTape() as t2:
        y=x*x*x
#     dy_dx = t2.gradient(y, x)
    
# d2y_dx2 = t1.gradient(dy_dx , x)

    

In [74]:
# assert dy_dx.numpy() ==3.0
# assert d2y_dx2.numpy()==6.0

In [88]:
#### using a sigmoid function for the derivative:
x =tf.constant([5.0])
with tf.GradientTape() as t:
    t.watch(x)
    y = tf.divide(1.0, tf.add(1.0, tf.exp(tf.negative(x))))

tf.print(y)
dy_dx= t.gradient(y, x)
tf.print(dy_dx)

[0.993307173]
[0.00664805667]


In [89]:
tf.print(dz_dx)

8


In [1]:
##### building an a simple ANN function ####


import numpy as np 
      
# # Each row is a training example, each column is a feature  [X1, X2, X3]
# X=np.array(([0,0,1],[0,1,1],[1,0,1],[1,1,1]), dtype=float)
# y=np.array(([0],[1],[1],[0]), dtype=float)

# # Define useful functions    

# # Activation function
# def sigmoid(t):
#     return 1/(1+np.exp(-t))

# # Derivative of sigmoid
# def sigmoid_derivative(p):
#     return p * (1 - p)

# # Class definition
# class NeuralNetwork:
#     def __init__(self, x,y):
#         self.input = x
#         self.weights1= np.random.rand(self.input.shape[1],4) # considering we have 4 nodes in the hidden layer
#         self.weights2 = np.random.rand(4,1)
#         self.y = y
#         self.output = np. zeros(y.shape)
        
#     def feedforward(self):
#         self.layer1 = sigmoid(np.dot(self.input, self.weights1))
#         self.layer2 = sigmoid(np.dot(self.layer1, self.weights2))
#         return self.layer2
        
#     def backprop(self):
#         d_weights2 = np.dot(self.layer1.T, 2*(self.y -self.output)*sigmoid_derivative(self.output))
#         d_weights1 = np.dot(self.input.T, np.dot(2*(self.y -self.output)*sigmoid_derivative(self.output), self.weights2.T)*sigmoid_derivative(self.layer1))
    
#         self.weights1 += d_weights1
#         self.weights2 += d_weights2

#     def train(self, X, y):
#         self.output = self.feedforward()
#         self.backprop()
        

# NN = NeuralNetwork(X,y)
# for i in range(1500): # trains the NN 1,000 times
#     if i % 100 ==0: 
#         print ("for iteration # " + str(i) + "\n")
#         print ("Input : \n" + str(X))
#         print ("Actual Output: \n" + str(y))
#         print ("Predicted Output: \n" + str(NN.feedforward()))
#         print ("Loss: \n" + str(np.mean(np.square(y - NN.feedforward())))) # mean sum squared loss
#         print ("\n")
  
#     NN.train(X, y)


for iteration # 0

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.79266259]
 [0.81670564]
 [0.82386397]
 [0.8403057 ]]
Loss: 
0.34976209628988036


for iteration # 100

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.49589323]
 [0.51073713]
 [0.50156393]
 [0.50880816]]
Loss: 
0.2481531281556321


for iteration # 200

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.27319157]
 [0.62973051]
 [0.5750561 ]
 [0.55581184]]
Loss: 
0.17530931162326968


for iteration # 300

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.1221552 ]
 [0.84479132]
 [0.81988486]
 [0.20146937]]
Loss: 
0.028010748530356913


for iteration # 400

Input : 
[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
Actual Output: 
[[0.]
 

In [58]:
def sigmoid(t):
    return 1/(1+np.exp(-t))

def numpy_to_tensor(something):

    something = tf.convert_to_tensor(something, dtype=tf.float32)
    return something
    
optimizer = tf.keras.optimizers.Adam()

class NeuralNetwork:
    def __init__(self, x,y):
        self.input = numpy_to_tensor(x)  # tensor input
        self.weights1= np.random.rand(self.input.shape[1],4) # considering we have 4 nodes in the hidden layer
        self.weights2 = np.random.rand(4,1)
        self.w1=tf.Variable(numpy_to_tensor(self.weights1)) # tensor weights
        self.w2=tf.Variable(numpy_to_tensor(self.weights2)) # tensor weights
        self.y = numpy_to_tensor(y)  # tensor output
        self.output = np.zeros(y.shape)
        self.output_tensor = numpy_to_tensor(self.output) # tensor output
        
        print(tf.shape(self.w1), tf.shape(self.w2))
        
    def train(self, iter):
        
        # feed forward using tensorflow:
        
        with tf.GradientTape() as t:
            # taking the first layer dot product:
            
            t.watch([self.w1, self.w2])
            self.first_dot_prd = tf.tensordot(self.input, self.w1, 1)
            self.layer1 = tf.divide(1.0, tf.add(1.0, tf.exp(tf.negative(self.first_dot_prd))))

            self.second_dot_prd = tf.tensordot(self.layer1, self.w2, 1)
#             with tf.GradientTape() as t2:
#             t2.watch(self.second_dot_prd)
            # taking the second layer dot product:

            self.layer2 = tf.divide(1.0, tf.add(1.0, tf.exp(tf.negative(self.second_dot_prd ))))
            self.loss = self.y-self.layer2   #tf.subtract(self.y, self.layer2)
            
            self.reduced_loss = tf.reduce_sum(tf.square(self.y - self.layer2))

#                 tf.print(self.loss)
            self.output=self.layer2

        
        loss=self.loss.numpy()
        
        if iter%5==0:
            print("Loss: "+str(np.square(np.mean(loss))))
        
        # doing a backward prop
        
        
        grad = t.gradient(self.reduced_loss, [self.w1, self.w2])
        
#         grad = tf.distribute.get_replica_context().all_reduce('sum', grad)
#         print(dw2)
#         dw1 = t.gradient(self.second_dot_prd, self.w1)
#         print(dw1)

#         print(grad)
#         print(self.w1, self.w2)
#         self.w1+=1e-1*grad[0]
#         self.w2+=1e-1*grad[1]
#         print(grad[0], grad[1])
        optimizer.apply_gradients(zip(grad,[self.w1,self.w2]))

        
            

    
            
        


In [61]:
            
X=np.array(([0,0,1],[0,1,1],[1,0,1],[1,1,1]), dtype=float)
y=np.array(([0],[1],[1],[0]), dtype=float)
            
NN = NeuralNetwork(X, y)
for i in range(100):
    NN.train(i)

tf.Tensor([3 4], shape=(2,), dtype=int32) tf.Tensor([4 1], shape=(2,), dtype=int32)
Loss: 0.046743385
Loss: 0.04598952
Loss: 0.04498322
Loss: 0.04382078
Loss: 0.042555574
Loss: 0.04122288
Loss: 0.039847992
Loss: 0.03844986
Loss: 0.037043072
Loss: 0.035639007
Loss: 0.034246635
Loss: 0.03287306
Loss: 0.031523865
Loss: 0.030203475
Loss: 0.028915294
Loss: 0.027661914
Loss: 0.026445292
Loss: 0.02526677
Loss: 0.024127262
Loss: 0.02302732
Loss: 0.021967124
Loss: 0.020946596
Loss: 0.01996547
Loss: 0.019023247
Loss: 0.01811931
Loss: 0.017252903
Loss: 0.016423201
Loss: 0.015629262
Loss: 0.014870113
Loss: 0.014144741
Loss: 0.013452079
Loss: 0.012791059
Loss: 0.012160602
Loss: 0.011559611
Loss: 0.010987004
Loss: 0.010441694
Loss: 0.009922615
Loss: 0.009428695
Loss: 0.008958882
Loss: 0.008512134
Loss: 0.008087448
Loss: 0.007683813
Loss: 0.0073002577
Loss: 0.006935841
Loss: 0.006589642
Loss: 0.006260787
Loss: 0.005948431
Loss: 0.005651758
Loss: 0.0053699967
Loss: 0.0051024
Loss: 0.004848268
Loss: 0.

In [81]:
# x=numpy_to_tensor(np.array(([0,0,1],[0,1,1],[1,0,1],[1,1,1]), dtype=float))

x= tf.ones((3, 4))

w1=numpy_to_tensor(np.random.rand(3,4))
y=tf.ones((4, 3))*2

tf.print(x, y)

tf.print(tf.tensordot(x, y, 1))


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] [[2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]]
[[8 8 8]
 [8 8 8]
 [8 8 8]]


In [58]:
tf.multiply(x, tf.transpose(w1))

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0.        , 0.        , 0.02300561],
       [0.        , 0.31643727, 0.3550229 ],
       [0.7240439 , 0.        , 0.07971293],
       [0.36281088, 0.07566915, 0.12640192]], dtype=float32)>

In [39]:
import numpy as np
import tensorflow as tf


# to read the training data and making use of vocabulary and index the chars:
# To read the training data and make a vocabulary and dictiornary to index the chars
class DataReader:
    def __init__(self, path, seq_length):
        #uncomment below , if you dont want to use any file for text reading and comment next 2 lines
        #self.data = "some really long text to test this. maybe not perfect but should get you going."
        self.fp = open(path, "r")
        self.data = self.fp.read()
        #find unique chars
        chars = list(set(self.data))
        #create dictionary mapping for each char
        self.char_to_ix = {ch:i for (i,ch) in enumerate(chars)}
        self.ix_to_char = {i:ch for (i,ch) in enumerate(chars)}
        #total data
        self.data_size = len(self.data)
        #num of unique chars
        self.vocab_size = len(chars)
        self.pointer = 0
        self.seq_length = seq_length

    def next_batch(self):
        input_start = self.pointer
        input_end = self.pointer + self.seq_length
        inputs = [self.char_to_ix[ch] for ch in self.data[input_start:input_end]]
        targets = [self.char_to_ix[ch] for ch in self.data[input_start+1:input_end+1]]
        self.pointer += self.seq_length
        if self.pointer + self.seq_length + 1 >= self.data_size:
            # reset pointer
            self.pointer = 0
        return inputs, targets

    def just_started(self):
        return self.pointer == 0

    def close(self):
        self.fp.close()
        



In [40]:
fp = open("temp.txt", "r")
data = fp.read()
#find unique chars
chars = list(set(data))
#create dictionary mapping for each char
char_to_ix = {ch:i for (i,ch) in enumerate(chars)}
ix_to_char = {i:ch for (i,ch) in enumerate(chars)}
#total data
data_size = len(data)
#num of unique chars
vocab_size = len(chars)
pointer = 0
seq_length = 5

In [41]:
def get_params(vocab_size, num_hidden):
    num_inputs = num_outputs = vocab_size

    def normal(shape):
        return tf.random.normal(shape=shape,stddev=0.01,mean=0,dtype=tf.float32)

    # Hidden layer parameters
    W_xh = tf.Variable(normal((num_inputs, num_hiddens)), dtype=tf.float32)
    W_hh = tf.Variable(normal((num_hiddens, num_hiddens)), dtype=tf.float32)
    b_h = tf.Variable(tf.zeros(num_hiddens), dtype=tf.float32)
    # Output layer parameters
    W_hq = tf.Variable(normal((num_hiddens, num_outputs)), dtype=tf.float32)
    b_q = tf.Variable(tf.zeros(num_outputs), dtype=tf.float32)
    params = [W_xh, W_hh, b_h, W_hq, b_q]
    return params

In [42]:
#defining the initial state:
def init_rnn_state(batch_size, num_hiddens):
    return (tf.zeros((batch_size, num_hiddens)), )

In [46]:
def rnn(inputs, state, params):
    # Here `inputs` shape: (`num_steps`, `batch_size`, `vocab_size`)
    W_xh, W_hh, b_h, W_hq, b_q = params
    H, = state
    outputs = []
    # Shape of `X`: (`batch_size`, `vocab_size`)
    for X in inputs:
        print('input',X.shape)
        X = tf.reshape(X,[-1,W_xh.shape[0]])
        H = tf.tanh(tf.matmul(X, W_xh) + tf.matmul(H, W_hh) + b_h)
        Y = tf.matmul(H, W_hq) + b_q
        print('output', Y)
        outputs.append(tf.math.argmax(Y[0]))
#     print('output', outputs.shape)
    return tf.concat(outputs, axis=0), (H,)

In [47]:
# defining the RNN layer CRUX:

class RNNModelScratch: #@save
    """A RNN Model implemented from scratch."""
    def __init__(self, vocab_size, num_hiddens,
                 init_state, forward_fn):
        self.vocab_size, self.num_hiddens = vocab_size, num_hiddens
        self.init_state, self.forward_fn = init_state, forward_fn

    def __call__(self, X, state, params):
        X = tf.one_hot(tf.transpose(X), self.vocab_size)
        X = tf.cast(X, tf.float32)
        return self.forward_fn(X, state, params)

    def begin_state(self, batch_size):
        return self.init_state(batch_size, self.num_hiddens)




In [48]:
num_hiddens=512
seq_len=5
X= tf.Variable([char_to_ix[ch] for ch in data[0:5]])
model=RNNModelScratch(23, num_hiddens, init_rnn_state, rnn)

state = model.begin_state(X.shape[0])
params = get_params(23, num_hiddens)
Y, new_state = model(X, state, params)
Y.shape, len(new_state), new_state[0].shape

input (23,)
output tf.Tensor(
[[-1.2685248e-03 -2.1264921e-03  9.7412511e-04  1.6114863e-03
  -4.2205822e-04 -2.5995141e-03 -1.8405751e-03  6.9634756e-05
   2.9907308e-03 -2.7920017e-03 -1.6235260e-03 -1.5650267e-03
   1.9201986e-03  1.8325539e-03  9.4695447e-04  3.6256784e-04
  -2.2264235e-03  5.1837876e-03  3.0615844e-03  1.3767412e-03
  -2.0205849e-04 -1.8630987e-03 -1.7162709e-03]
 [-1.2685248e-03 -2.1264921e-03  9.7412511e-04  1.6114863e-03
  -4.2205822e-04 -2.5995141e-03 -1.8405751e-03  6.9634756e-05
   2.9907308e-03 -2.7920017e-03 -1.6235260e-03 -1.5650267e-03
   1.9201986e-03  1.8325539e-03  9.4695447e-04  3.6256784e-04
  -2.2264235e-03  5.1837876e-03  3.0615844e-03  1.3767412e-03
  -2.0205849e-04 -1.8630987e-03 -1.7162709e-03]
 [-1.2685248e-03 -2.1264921e-03  9.7412511e-04  1.6114863e-03
  -4.2205822e-04 -2.5995141e-03 -1.8405751e-03  6.9634756e-05
   2.9907308e-03 -2.7920017e-03 -1.6235260e-03 -1.5650267e-03
   1.9201986e-03  1.8325539e-03  9.4695447e-04  3.6256784e-04
  -2.2

(TensorShape([5]), 1, TensorShape([5, 512]))

In [38]:
Y[0]

<tf.Tensor: shape=(23,), dtype=float32, numpy=
array([ 3.5496957e-03, -1.5880831e-03, -8.1366283e-04, -7.4636005e-04,
       -2.1743190e-03, -2.1476911e-03, -1.6094119e-03,  1.0846057e-03,
       -6.8735047e-03,  9.2799775e-04,  5.2702031e-05, -1.5214975e-03,
        2.2887054e-04,  5.2304380e-04, -3.5918376e-04,  2.3214282e-03,
       -2.1889429e-03, -4.2013042e-03,  6.2897464e-04,  1.5773850e-03,
        2.7675428e-03, -7.9500768e-04, -2.6871930e-03], dtype=float32)>

In [36]:
something=tf.math.argmax(Y[0])

In [37]:
tf.print(something)

0
